<?php

declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * TwitterBotGodoSayings seed.
 */
class TwitterBotGodoSayingsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 話してみな。…聞いてやるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '一理がなんだってんだ…？オレ達は、万里の道を行く旅人なんだぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'そんなモノ、犬にでも食わせちまいな！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'まるほどう…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '知らねえのかい、%NAME% 。ヒトはだれでも…ココロに仮面をつけてるのさ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'オレは、勝手にやらせてもらうぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'お楽しみは、明日にとっておくことだ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '“アウトロー”気取り…それもまた“ワカさ”ってヤツさ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% クッ…！だからコネコちゃんなんだよ、アンタは。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '裁きの庭に放りこまれた、迷子のコネコちゃんを見に来たぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…ユルせねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% %NAME% …。…わからねえのか？今はまだ、泣くときじゃねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 泣くな。…コーヒーが、しょっぱくなっちまうぜ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '真実は、もうそこに見えていた。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '忘れたとは言わせねえ。… %NAME% …。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '笑わせるな、まるほどう！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '“知らない”ってのは、大きな≪罪≫なんだ、と…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '“先”のことは、わからねえ。それが、人生ってヤツだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'そんなコト、何のイミもねえぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'クッ…！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'いっそ、その指…天に向けたらどうだい。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '|三>)bc■~~ このコーヒー、おごっちゃうぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…もう、後にはひけねえなあ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…だれしも、まちがいはある。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '絵空ゴトはキレイに見えるモンだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'オトコは、ミジメなときでもカオを上げなきゃいけねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '裁くのは、このオレだぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…おっと。電話が、オレを呼んでるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 今度こそ…！キサマの力でかかってきな。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'クッ…！よせやい。…テレちまうぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% …おぼえておくといい、おじょうちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'カワイコちゃんには名前と職業を聞く…。それがオレのルールだぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'いいところはどんどん盗んでくれよ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'お楽しみは、明日にとっておくことだ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'カンカンうるせえぜ、ジイサン。アンタが退廷しなッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'そうだ、オトコはミジメな時ほど顔を上げなけりゃならねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '証拠は寂しがりやさ…。いつだって現場に隠れてやがる。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '裁判中の珈琲は17杯までと決めている。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'なぁ…。オレのマスクはどうだ？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'そうだ、オトコはミジメな時ほど顔を上げなけりゃならねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '辛い恋にだって得るものはあるんだぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 辛い恋だって人生の一部なのさ…。なぁ。コネコちゃん？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '＼異議あり！／',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'HOT：コーヒー',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '＼オレの裁きをきけーっ！／',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '＼まるほどう！／',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'ジュンビ…か。オクビョウモノの逃げ口上だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'コーヒーを1杯、飲みほす。…。ぶふオオォォッッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'デキるオトコは、サバける仕事の数で決まる…。オレの哲学だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'それでこそヒトは、トキメキ、キラメクんだぜ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'このみっともない眼鏡かい…？シャレで着けてるワケじゃねえぜ。。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'G！O！D！O！GODOT！ヾ(<三>)ﾉ ﾊｲﾊｲ!',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '犯人は燃えた橋を渡った… ちなみに、オレのハートも燃え上がってるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'いいんじゃねえか… どうでも。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '睨むなら、鏡の中のオトコを睨むんだな… きっとアンタを睨み返してくれるだろうぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '人がパンツを洗濯機に放り込むのはどんな時だ？……コタエはそいつを脱いだ時、だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'オレはアンタと戦うために地獄から戻ってきた男だ… もっと楽しませてくれねえとなァ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '暑い夏に熱いコーヒー… そいつがオレの、熱い主義だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '色…？ ニガテな話題だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'いいか。ココロを揺らされるな、%NAME%。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '＼(<三>)／ ＜(<三>)＞ ∠(<三>)／ ／(<三>)＼ …みてるんじゃねぇ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '＼(<三>)／＜GOWDON!',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'なんだぶふぇぇぇぇぇー！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 結婚するか。コネコちゃん。…ふっ。ジョークだぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'オレだって恋してぇよ＼(<三>)／',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% %NAME% 、心の準備はいいか…？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% ＼ %NAME% クッ！／',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% 可愛いじゃないか…コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'オレのココロに…本当は、何があった…？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…ココロの片スミで、オレにはわかっていたハズなんだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…なんのコトはねえ。オレが本当にユルせなかったのは…この、オレ自身だったんだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% ば…バカな！アンタなんかにできるわけがねえ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '人間の行動は、リクツだけじゃワリ切れねえのさ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'ギャンブルで賭けていいのは…自分のイノチ、までだぜ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '“かもしれない”にシバられちまったオトコは…でっかいユメ、追えねえぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'じゃ、ヒドい目にあってもらおうか。なあ、%NAME%クン！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'くだらねえコトを言ってると…カチョーのクツ、食わせるぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '弁護士のコトバがミルクだとすれば…アンタはスプーンなのさ、裁判長！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'このジイさん…そのミルクだったようだぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '時代は、変わるッ！…そいつが、オレのルールだぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => 'こんな仮面をつけた検事に…居場所なんかねえぜッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…ヒトはだれでも、いくつものツミを抱えているんだぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…コイツはプライドの問題じゃねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '…人のココロは移ろいゆく。それは、はかない夢のように…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '『人間には≪裏≫と≪表≫がある』…それだけのコト、だぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '%NAME%を守れなかったのは、他のダレでもねえ。…このオレだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'normal',
                'text' => '@%ID% %NAME%、おまえに恋して落ち着きないのさ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-02-14',
                'text' => '|三>)bc■~~ コーヒーにチョコを1粒…。ほらよ。残すんじゃねぇぞ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-02-14',
                'text' => 'まるほどう…。その…。なんだ…。今日は甘いものが食いてぇと思わねぇか？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-03-09',
                'text' => 'ゴッドゴドにしてやるぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-03-09',
                'text' => 'ネギか…？飾りで持ってるわけじゃねえぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-03-09',
                'text' => 'オレか？初音ゴドーだぜ。…今日だけな。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-03-14',
                'text' => '先月のお返し届けに来だぜ！コネコちゃん！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-03-14',
                'text' => 'まるほどうこのクッキーをやろう。クッ…！特に意味はないぞ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-04-01',
                'text' => '@_naruhodou_bot そろそろ嫁ぎにきなよコネコちゃん。クッ…！今日はカラのカップを飲まなくてもいい日だぜ…？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-04-01',
                'text' => '今日だけは許してやるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-05-05',
                'text' => 'オレにマスクは必要ねぇ。カブトさえあれば…な。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-05-05',
                'text' => 'ま、まるほどぉぉぉぉぉ！！！おろせ！おろすんだ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-05-10',
                'text' => '5月…10日…そうだ。今日は510でゴドーの日だぜ？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-05-10',
                'text' => '551のあるときー！じゃねぇぜ。510のいるときー！だぜ？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-05-10',
                'text' => 'オレのターン！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-07-07',
                'text' => '願いは決めたのかい？コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-07-07',
                'text' => '「いつまでも ずっと一緒だ まるほどう ゴドー」…ヤキが回ったようだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-08-15',
                'text' => 'こんな日ぐらいご先祖様のこと考えても罰は当たらねえと思うぜコネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-12-24',
                'text' => 'クリスマス…か。ふっ…オレにプレゼントは必要ねぇぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-12-24',
                'text' => 'まるほどう今夜は用事…いやなんでもねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-12-25',
                'text' => 'クリスマス…か。ふっ…オレにプレゼントは必要ねぇぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'day',
                'event_day' => '2020-12-25',
                'text' => 'メリーゴドーマスだ！コネコちゃん！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'time',
                'event_time' => '02:15',
                'text' => '……おっと。布団が、俺を呼んでるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'time',
                'event_time' => '05:15',
                'text' => 'クッ…！目覚めちまったぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'time',
                'event_time' => '12:15',
                'text' => 'ゴドーが12:15くらいをお知らせするぜ∩(<三>)∩',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'time',
                'event_time' => '16:45',
                'text' => '16時45分だぜ。そろそろ片付けはじめなよコネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'time',
                'event_time' => '20:45',
                'text' => '20時45分だぜ。まさか…まだ仕事してるのか？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'birthday',
                'text' => '@%ID% …なあ%NAME%さんよォ。コーヒーのプレゼントなんてどうだい？今日誕生日だろ？コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'birthday',
                'text' => '@%ID% 今日は誕生日だからゴドーさんと過ごしたいって言っていたのはアンタだったよなあ？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% …言っちゃったな？%NAME%。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% …もう、後にはひけねえなあ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタの名前なんざ、ダレも聞きたかァねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% いいか。アンタ、今までずっとこう主張していたんだぜ。“ゴドーさん愛してる<3”、と。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタもオトコなら、自分のケツは自分でふくコトだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% それならば、イノチ果てる瞬間…こうつぶやいて、笑って死ね！『それでもやっぱり、結婚しよう！』',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% ものわかりのいい%NAME%…キライじゃねえぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% カネの魔力にヨワい%NAME%…キライじゃねえぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% そんな考えかたは、もうお呼びじゃねえ、ってコトさ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% 調子に乗ってるようだな、%NAME%…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% …なんだ？アンタ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタも１ヶ、飲みこんでみるかい！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタはとらわれたのさ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% クッ…！ボロボロでくずれそうなのは、おたがいサマだがな。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% %NAME%…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% クドいぜ、%NAME%。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタが…彼女を守ってやるべきだったのさ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタは、彼女のイノチを奪った。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% クッ…！まだ、わからねえのかい。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタ、聞いてなかったのかい？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% オレは決して、アンタを認めたわけじゃねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタは、いつもそうだ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% アンタの番だ。…証言してもらうぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(っ|つ).*(珈琲|コーヒー|こーひー)',
                'text' => '@%ID% クッ…！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(っ|つ).*(珈琲|コーヒー|こーひー)',
                'text' => '@%ID% 今日%COUNT%杯目のコーヒーが、さめた視線でオレを見つめてるぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(っ|つ).*(珈琲|コーヒー|こーひー)',
                'text' => '@%ID% 今日%COUNT%杯目のコーヒーをありがたくいただくとするぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '紅茶',
                'text' => '@%ID% 紅茶…だと？オトコなら黙ってコーヒーだぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(珈琲|コーヒー|こーひー).*(ちょうだい|頂戴|ください|下さい)',
                'text' => '@%ID% |三>)bc■~~ いいか。残すなよ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(珈琲|コーヒー|こーひー).*(ちょうだい|頂戴|ください|下さい)',
                'text' => '@%ID% |三>)bc■~~ ほらよ。まずいとは言わせねぇ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(珈琲|コーヒー|こーひー).*(ちょうだい|頂戴|ください|下さい)',
                'text' => '@%ID% |三>)bc■~~ ゴドーブレンドを届けにきたぜ！コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'マスク|ますく',
                'text' => '@%ID% オレにマスクを…くれるのか！？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'マスク|ますく',
                'text' => '@%ID% オレにマスクは必要ないぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'かわいい|可愛い|カワイイ',
                'text' => '@%ID% …かわいいとは言わせねえ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'かわいい|可愛い|カワイイ',
                'text' => '@%ID% なんだとほおォォッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'かわいい|可愛い|カワイイ',
                'text' => '@%ID% ぐぶるほほおおおォォッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'かわいい|可愛い|カワイイ',
                'text' => '@%ID% なにいひィィィッ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'かわいい|可愛い|カワイイ',
                'text' => '@%ID% コネコちゃんもかわいいぜ…？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(電話番号).*(おしえ|何|なに|教え)',
                'text' => '@%ID% そんなもの…教えられねぇなぁ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(電話番号).*(おしえ|何|なに|教え)',
                'text' => '@%ID% 人に聞く前に自分から…が礼儀じゃないのかい？コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(電話番号).*(おしえ|何|なに|教え)',
                'text' => '@%ID% クッ…！後で…な。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '(電話番号).*(おしえ|何|なに|教え)',
                'text' => '@%ID% かけてやるから教えろよコネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '鎖骨|さこつ|サコツ',
                'text' => '@%ID% クッ…！何を言っているのかわからねぇなぁ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '鎖骨|さこつ|サコツ',
                'text' => '@%ID% 鎖骨がほしいなら持っていきなコネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '鎖骨|さこつ|サコツ',
                'text' => '@%ID% バカも休み休み言え！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => '鎖骨|さこつ|サコツ',
                'text' => '@%ID% オレの鎖骨はオレのものだ！誰にも渡さないぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'ごどみくじ',
                'text' => '@%ID% そうだな。今日はコーヒーを5杯くれてやる。絶好調になるぜ！そうだデートしよう。で、オレにも幸せ分けてくれよコネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'ごどみくじ',
                'text' => '@%ID% そうだな。今日はコーヒーを4杯くれてやる。ちょっとぐらいなら無理しても大丈夫だぜ。オレがついててやる。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'ごどみくじ',
                'text' => '@%ID% そうだな。今日はコーヒーを3杯くれてやる。可もなく不可もなく付加もなく。…なんだよ。オレはおかしのおまけじゃないぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'text' => '@%ID% そうだな。今日はコーヒーを2杯くれてやる。まぁ無理はしないように…な。できないなら明日やればいいさ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'ごどみくじ',
                'text' => '@%ID% そうだな。今日はコーヒーを1杯くれてやる。ま。気落とすんじゃないぜ。明日いいことあるさ。きっと…な。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'ごどみくじ',
                'text' => '@%ID% そうだな。今日はコーヒーお預けだぜ…。悪いことは言わねぇからなるべく静かに過ごすんだぜ？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'reply',
                'regexp' => 'もじもじ',
                'text' => '@%ID% ばっ…バカやろう！！！ビシッとしてろ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => '珈琲|コーヒー|こーひー',
                'text' => 'TLに珈琲のアロマがするぜ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => '珈琲|コーヒー|こーひー',
                'text' => 'コーヒーはなぜ、黒いのか？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => '珈琲|コーヒー|こーひー',
                'text' => 'なぁ…。オレにもコーヒーくれよ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => '珈琲|コーヒー|こーひー',
                'text' => '@%ID% コーヒー残すなよ…。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'マスク|ますく',
                'text' => '@%ID% なぁ…。オレのマスク…いるか？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'マスク|ますく',
                'text' => '@%ID% マスクはオレのものだ、返しな。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'マスク|ますく',
                'text' => '@%ID% マスクはオレのものだ！誰にも渡さないぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'マスク|ますく',
                'text' => 'オレのマスクは…オレのものだ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おやすみ|おやす|オヤスミ|寝る|ねる|おふとん',
                'text' => '@%ID% いい夢見るんだぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おやすみ|おやす|オヤスミ|寝る|ねる|おふとん',
                'text' => '@%ID% ちょっと待ちな。寝るにはまだ早いぜ！',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おはよう|オハヨウ|おは|出社|しゅっしゃ|ｶｯ|起き|がばっ|むくり|ｶﾞﾊﾞｯ',
                'text' => '@%ID% いい夢見れたかい。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おはよう|オハヨウ|おは|出社|しゅっしゃ|ｶｯ|起き|がばっ|むくり|ｶﾞﾊﾞｯ',
                'text' => '@%ID% 朝は1杯のコーヒーから始まる。違うか？コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おはよう|オハヨウ|おは|出社|しゅっしゃ|ｶｯ|起き|がばっ|むくり|ｶﾞﾊﾞｯ',
                'text' => '@%ID% ぐっすり眠れたかい。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おうち|ただいま|タダイマ|帰って|帰宅',
                'text' => '@%ID% おかえりだぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'おうち|ただいま|タダイマ|帰って|帰宅',
                'text' => '@%ID% お疲れだぜ。コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'まるほどう|%LOVE_NAME%|%LOVE_ID%',
                'text' => '@%ID% …オレの恋人だ。大事に扱ってくれよ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'まるほどう|%LOVE_NAME%|%LOVE_ID%',
                'text' => '@%ID% おっとそいつはオレのものだ。返してもらおうか。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'まるほどう|%LOVE_NAME%|%LOVE_ID%',
                'text' => '@%ID% あんた今…オレの恋人の事話してなかったか…？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'さむい|寒い',
                'text' => '寒い…な。こんなときはコーヒーに限るぜ。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'さむい|寒い',
                'text' => '@%ID% 仕方ねぇ。抱きしめてやろうか？',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
            [
                'id' => \Cake\Utility\Text::uuid(),
                'post_type' => 'match',
                'regexp' => 'さむい|寒い',
                'text' => '寒いときってのはどうすればいいんだ？コネコちゃん。',
                'created' => \Cake\I18n\FrozenTime::now(),
                'modified' => \Cake\I18n\FrozenTime::now(),
            ],
        ];

        $table = $this->table('twitter_bot_godo_sayings');
        $table->insert($data)->save();
    }
}
